site_name: neuron-catalog
site_url: http://strawlab.org/neuron-catalog/
site_description: A simple web database for keeping track of neurons.

repo_url: https://github.com/strawlab/neuron-catalog/

pages:
- ['index.md', 'Introduction']
- ['demo-mode.md', 'User Guide', 'Demonstration Mode']
- ['installation.md', 'User Guide', 'Installation']
- ['security.md', 'User Guide', 'Security']
- ['settings.md', 'User Guide', 'Settings']
- ['specializations.md', 'User Guide', 'Species Specific Specializations']
- ['credits.md', 'About', 'Credits']
- ['license.md', 'About', 'License']
- ['release-notes.md', 'About', 'Release Notes']
