---
- name: Meteor server
  hosts: 127.0.0.1
  tasks:

   - name: Check meteor existence
     stat: path=/usr/local/bin/meteor
     register: usr_local_bin_meteor

   - name: install meteor
     shell: curl https://install.meteor.com | /bin/sh
     when: not usr_local_bin_meteor.stat.exists

   - apt: name=supervisor state=installed

   - name: install meteor supervisor script
     copy: src=neuron-catalog-meteor.conf dest=/etc/supervisor/conf.d/neuron-catalog-meteor.conf mode=0644 owner=root group=root
   - supervisorctl: name=neuron-catalog-meteor state=present
